CP-15835: chore(github): Add CODEOWNERS file
Cloudzero/cloudzero-oci-cost-adaptor pull request #4
Opened 2023-12-31 16:34 UTC by Tankanow

This PR adds a CODEOWNERS file to the repo, assigning ownership to [@cloudzero/stratus].

2024-01-08 15:32 UTC, nina-roche commented
I (nor the team I think) have touched this adaptor. Is there an existing adaptor out there being used by a customer?

2024-01-23 00:06 UTC, intjonathan commented
@nina-roche I am a customer, I wrote and use this daily. I guess you could assign it to @intjonathan if you wanted?

2024-01-24 22:30 UTC, adamrice32 commented
All, we're going to revert this PR, and keep the reviewers list pointed at CloudZero's internal security team. This is by design for any open source style repos that we support. @Tankanow FYI

2024-01-25 11:13 UTC, adamrice32 requested changes
@Tankanow Please revert this PR at your earliest convenience.

2024-01-29 01:06 UTC, closed without merging